In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_1 = pd.read_csv('df_final_web_data_pt_1.txt')
df_2 = pd.read_csv('df_final_web_data_pt_2.txt')

In [4]:
df_2

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
412259,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
412260,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
412261,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
412262,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
412263,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [5]:
df_1.columns = df_1.columns.str.strip().str.lower().str.replace(" ", "_")
df_2.columns = df_2.columns.str.strip().str.lower().str.replace(" ", "_")

In [6]:
df_2.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [ ]:
#df_2 = df_2.drop_duplicates()
#df_1 = df_1.drop_duplicates()

In [18]:
df_2.process_step.unique()

array(['confirm', 'step_3', 'step_2', 'step_1', 'start'], dtype=object)

In [7]:
col = "date_time"
summary_data = df_2[col].describe(percentiles=[0.25, 0.5, 0.75])
print(summary_data)

count                  412264
unique                 346697
top       2017-05-02 10:53:01
freq                       24
Name: date_time, dtype: object

In [11]:
df_2.client_id.duplicated().sum()

344834

In [26]:
df_2.client_id.value_counts().sum() + df_1.client_id.value_counts().sum()

755405

In [10]:
df_2[df_2.duplicated()]

,client_id,visitor_id,visit_id,process_step,date_time
125,3751049,937925261_74821699083,628817270_45049432060_475841,start,2017-05-15 23:09:44
143,9912156,746623513_52101087617,780044921_57678038107_984942,start,2017-05-03 14:09:52
326,5786602,893139880_61416949586,747153834_69434320996_858907,start,2017-05-10 01:49:09
328,5786602,893139880_61416949586,747153834_69434320996_858907,start,2017-05-10 01:48:45
375,5786602,893139880_61416949586,119968876_5423296886_390511,start,2017-06-08 02:14:09
...,...,...,...,...,...
412120,1672289,658797407_91003097342,430110748_90347503221_597628,start,2017-05-01 19:28:53
412163,4408245,14058946_73585431797,994148957_84373994761_991865,start,2017-06-06 09:17:23
412165,4408245,14058946_73585431797,994148957_84373994761_991865,start,2017-06-06 09:09:44
412167,4408245,14058946_73585431797,994148957_84373994761_991865,start,2017-06-06 08:51:16
412217,3897324,80177429_24869309091,149796456_64325617570_112561,start,2017-05-04 08:21:30

In [19]:
df_merged = pd.concat ( [df_2, df_1], ignore_index=True
    
)

In [27]:
df_merged

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
755400,2443347,465784886_73090545671,136329900_10529659391_316129,confirm,2017-03-31 15:15:46
755401,2443347,465784886_73090545671,136329900_10529659391_316129,step_3,2017-03-31 15:14:53
755402,2443347,465784886_73090545671,136329900_10529659391_316129,step_2,2017-03-31 15:12:08
755403,2443347,465784886_73090545671,136329900_10529659391_316129,step_1,2017-03-31 15:11:37
755404,2443347,465784886_73090545671,136329900_10529659391_316129,start,2017-03-31 15:10:47

In [28]:
df_merged.to_csv('df_final_web_data_clean')