In [ ]:
import pandas as pd
import

In [5]:
df = pd.read_csv('df_final_demo_cleaned')

In [6]:
df.isnull().sum()

Unnamed: 0          0
client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
dtype: int64

In [24]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [client_id, clnt_tenure_yr, clnt_tenure_mnth, clnt_age, gendr, num_accts, bal, calls_6_mnth, logons_6_mnth]
Index: []

In [21]:
df['clnt_age'] = df['clnt_age'].fillna(df['clnt_age'].mean())

In [27]:
df = df.drop_duplicates()

In [29]:
df.gendr.unique()

array(['U', 'M', 'F', 'X'], dtype=object)

In [11]:
df

,Unnamed: 0,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,59771,169,21,262,47.5,M,2,501570.72,4,4
1,40126,555,3,46,29.5,U,2,25454.66,2,6
2,1532,647,12,151,57.5,M,2,30525.80,0,4
3,58466,722,11,143,59.5,F,2,22466.17,1,1
4,13142,934,9,109,51.0,F,2,32522.88,0,3
...,...,...,...,...,...,...,...,...,...,...
70590,30538,9999400,7,86,28.5,U,2,51787.04,0,3
70591,3228,9999626,9,113,35.0,M,2,36642.88,6,9
70592,48756,9999729,10,124,31.0,F,3,107059.74,6,9
70593,8011,9999832,23,281,49.0,F,2,431887.61,1,4
70594,53845,9999839,13,160,28.5,F,2,67425.35,3,3

In [30]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [41]:
df = df.sort_values(by="client_id", ascending=True)

In [10]:
df["clnt_tenure_yr"] = df["clnt_tenure_yr"].astype(int)
df["clnt_tenure_mnth"] = df["clnt_tenure_mnth"].astype(int)
df["num_accts"] = df["num_accts"].astype(int)
df["calls_6_mnth"] = df["calls_6_mnth"].astype(int)
df["logons_6_mnth"] = df["logons_6_mnth"].astype(int)

In [9]:
df.clnt_tenure_mnth.unique()

array([262.,  46., 151., 143., 109., 145.,  66.,  99.,  85., 576., 177.,
        60., 150., 139., 229., 280., 260., 110., 157.,  98.,  63., 179.,
       231., 142.,  58., 117., 116., 189., 190.,  75.,  94., 172., 199.,
       154.,  86.,  77., 253., 361.,  57., 173.,  92., 329.,  72.,  81.,
       149., 155.,  89., 195., 141., 106., 252., 218., 364., 140., 241.,
       257., 226., 269., 170., 164.,  78., 108.,  56., 105.,  88., 211.,
       205.,  73., 194.,  69., 171., 126.,  71.,  83., 121., 299., 156.,
       285., 191., 321., 200.,  55.,  76., 242., 281., 294., 224., 166.,
        70., 304.,  65., 169., 264., 230., 222., 160., 192.,  74.,  84.,
        82., 168., 124., 119., 342., 219., 163., 144., 193., 131., 118.,
       158.,  87., 186., 107., 196.,  91., 277., 125., 122., 259., 178.,
       123., 310., 181., 232., 352., 214., 114., 250., 101.,  59., 345.,
       282.,  80., 129.,  68., 184., 174., 268., 246., 176., 183.,  95.,
        48., 255., 215., 100., 298., 187., 355., 318.,  90., 209., 245.,
       137., 248., 284., 274., 228., 247., 359., 339.,  50.,  64., 254.,
       130., 138., 276.,  44., 136., 271.,  54., 133.,  62., 319., 290.,
        93., 216., 152., 289., 261., 362., 113., 103., 212., 206.,  67.,
       516., 322., 391., 202., 279., 331., 313., 337., 182., 343.,  79.,
       272., 295., 369., 115., 288., 238., 161., 112., 373., 371., 134.,
       225., 127., 148., 201., 147., 102., 165., 220., 128., 330., 132.,
       414., 296., 349., 185., 162., 273., 408.,  37., 258., 120.,  97.,
       188., 243.,  53., 301., 308., 286., 370., 317., 315.,  47., 328.,
       300., 197., 283., 111., 208., 167., 135., 346., 217., 180., 239.,
       204., 338., 153., 305.,  61., 249., 367., 442., 667., 263., 104.,
       267., 210., 159., 348., 320., 354.,  49., 198., 397., 234., 428.,
       287.,  96., 292., 251., 336., 291., 406., 334., 223., 347., 275.,
        52., 411., 256., 326., 396., 270., 325., 236., 175., 221., 203.,
       213., 418.,  34., 312., 613., 311., 344., 240., 146.,  39., 233.,
       227., 358.,  45., 266., 392., 207., 265., 404., 237.,  36.,  38.,
        41., 375., 306., 297., 335., 314., 429., 432., 278., 368., 327.,
       453., 385.,  43., 293., 340., 427., 462., 447., 749.,  40., 394.,
       387., 316.,  35., 376., 422., 407., 360., 302., 386., 409., 341.,
       384., 390., 382., 332., 235., 395., 309., 379., 365., 324., 323.,
       381., 484., 419., 372., 303., 439., 401., 410., 403., 464.,  51.,
       550., 402., 420., 244., 398., 473.,  42., 380., 430., 353., 351.,
       413., 357., 421., 431., 436., 378., 416., 307., 377., 363., 423.,
       425., 389., 350., 610., 383., 445., 624.,  33., 571., 535., 479.,
       463., 393., 356., 333., 482., 388., 366., 417., 460., 454., 441.,
       603., 426., 480., 433., 424., 504., 668., 400., 459., 512., 507.,
       492., 399., 451., 581., 415., 461., 614., 532., 444., 669., 468.,
       526., 434., 374., 448., 511., 602., 465., 466., 483., 561., 412.,
       457., 475., 446., 449., 564., 509., 655., 485., 569., 450., 443.,
       562., 455., 563., 593., 554., 661., 608., 405., 585., 481., 596.,
       472., 456., 469., 440., 589., 631., 586., 612., 539.])

In [12]:
df.to_csv('df_final_demo_cleaned')

In [7]:
df_expe = pd.read_csv('df_final_experiment_clients.txt')

In [33]:
df_expe.isnull().sum()

client_id        0
Variation    20109
dtype: int64

In [38]:
df_expe

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

In [47]:
df_expe[df_expe.isnull().any(axis=1)]

Empty DataFrame
Columns: [client_id, variation]
Index: []

In [ ]:
df_expe = df_expe.drop_duplicates()

In [36]:
df_expe = df_expe.dropna()

In [45]:
df_expe.columns = df_expe.columns.str.strip().str.lower().str.replace(" ", "_")

In [46]:
df_expe.variation.unique()

array(['Test', 'Control'], dtype=object)

In [49]:
df.to_csv('df_final_demo_cleaned')
df_expe.to_csv('df_final_experiment_clients_cleaned')